wandb_version: 1

LR:
  desc: null
  value: 1.0e-05
SPP_info:
  desc: null
  value:
    position: Near bottleneck
    used: true
Scehduler:
  desc: null
  value: CosineAnnealling
_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1637473867
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      - 17
      4: 3.7.10
      5: 0.12.7
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 2
folds:
  desc: null
  value: 1
img_shape:
  desc: null
  value: 16
model_conf:
  desc: null
  value:
    activation: relu
    c: 3
    input_shape:
    - 1
    - 32
    - - 16
      - 16
      - 16
    n_labels: 3
    normalizaiton: group_normalizaiton
