# INITIAL SETTINGS

device: 'cuda:1'
seed: 12536
debug: False

dataset:
  data_path: "/nfs/Workspace/brats_brain_segmentation/data/BraTS2021_data/training"
  teacher_model: False # True
  num_workers: 16 # batch_size * ngpu
  batch_size: 1
  img_size: [160, 160, 160]
    
augs:
  apply: True
  aug_name:  # flip, rotate, shift, brightness, elastic_transform
  aug_type: "multiple" # robust
  aug_prob: 0.75
  min_angle: -30
  max_angle: 30
  max_percentage: 0.4

model:
  normalization: "group_normalization" # batch_normalization
  activation: "relu" # elu, leakyrelu

optimizer:
  optim: "adam" # Ranger, AdamW
  lr: 25e-5
  wd: 1e-7

criterion: "SoftDiceLossSquared" # DC_and_Focal_loss, EDiceLoss, FocalLoss

scheduler: "CosineAnnealingLR" # CosineAnnealingWarmRestarts

train:
  resume: 
  epochs: 10

logger:
  project_name: "BraTS_dec9" # BraTS_resume, BraTS_folds

com: "multiple augs" # Comment